# Generated by Django 3.2 on 2021-05-20 16:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.CharField(max_length=255)),
                ('price_for_junior', models.IntegerField(default=0)),
                ('price_for_senior', models.IntegerField(default=0)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_line_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\+\\d+$', 'Invalid Country Code.')])),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Invalid Phone Number')])),
                ('reg_no', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^(C|I|E)(2K)[0-9]+$', 'Invalid Registration Number')])),
                ('senior', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_password', models.CharField(max_length=8, unique=True)),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('event_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.event')),
                ('user_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_line_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eventline'),
        ),
    ]
